export const Concessionaire = [
  { id: 1, name: 'Amazonas Energia' },
  { id: 2, name: 'CELESC-SC' },
  { id: 3, name: 'CEMAR - Companhia Energética do Maranhão' },
  { id: 4, name: 'CELPE' },
  { id: 5, name: 'CEMIG' },
  { id: 6, name: 'COPEL' },
  { id: 7, name: 'CPFL Paulista' },
  { id: 8, name: 'CPFL Piratininga' },
  { id: 9, name: 'CPFL RGE' },
  { id: 10, name: 'CPFL Santa Cruz' },
  { id: 11, name: 'DMED' },
  { id: 12, name: 'EDP ES' },
  { id: 13, name: 'EDP SP' },
  { id: 14, name: 'ELFSM' },
  { id: 15, name: 'Enel CE' },
  { id: 16, name: 'Enel RJ' },
  { id: 17, name: 'Enel SP' },
  { id: 18, name: 'Energisa AC' },
  { id: 19, name: 'Energisa PB' },
  { id: 20, name: 'Energisa Minas-Rio' },
  { id: 21, name: 'Energisa MS' },
  { id: 22, name: 'Energisa MT' },
  { id: 23, name: 'Energisa PB' },
  { id: 24, name: 'Energisa RO' },
  { id: 25, name: 'Energisa SE' },
  { id: 26, name: 'Energisa Sul Sudeste' },
  { id: 27, name: 'Energisa TO' },
  { id: 28, name: 'Equatorial AL' },
  { id: 29, name: 'Equatorial CEA AP' },
  { id: 30, name: 'CEEE - RS' },
  { id: 31, name: 'Equatorial GO' },
  { id: 32, name: 'Equatorial MA' },
  { id: 33, name: 'Equatorial PA' },
  { id: 34, name: 'Equatorial PI' },
  { id: 35, name: 'Light' },
  { id: 36, name: 'Neoenergia Brasília' },
  { id: 37, name: 'Neoenergia COELBA' },
  { id: 38, name: 'Neoenergia RN' },
  { id: 39, name: 'Neoenergia Elektro' },
  { id: 40, name: 'Neoenergia Elektro' },
  { id: 41, name: 'Neoenergia PE' },
  { id: 42, name: 'Roraima Energia' },
  { id: 43, name: 'Sulgipe' },
  { id: 44, name: 'Energisa SP' },
];
